export enum PostCategory {
    SP = 'street photography',
    ANIMALS = 'animals',
    FASHION = 'fashion',
    NATURE = 'nature',
    PORTRAIT = 'portrait',
    ARCHI = 'architecture',
    FOOD = 'food and drinks',
    PEAOPLE = 'people',
    TRAVEL = 'travel',
    ART = 'art & culture',
    ATHLETICS = 'athletics',
    FILM = 'film',
    WALLPAPER = 'wallpaper',
    UNDEFINED = 'undefined',
}